model:
    chemical_species: 'univ'
    cutoff: 6.0
    multi_cutoff: [6, 4, 6]
    channel: 128
    is_parity: False
    lmax: 4
    num_convolution_layer: 3
    irreps_manual:
        - "128x0e"
        - "128x0e+64x1e+32x2e+32x3e+32x4e"
        - "128x0e+64x1e+32x2e+32x3e+32x4e"
        - "128x0e"

    weight_nn_hidden_neurons: [64, 64]
    radial_basis:
        radial_basis_name: 'bessel'
        bessel_basis_num: 8
    cutoff_function:
        cutoff_function_name: 'XPLOR'
        cutoff_on: 5.0

    act_gate: {'e': 'silu', 'o': 'tanh'}
    act_scalar: {'e': 'silu', 'o': 'tanh'}

    conv_denominator: 'avg_num_neigh'
    train_shift_scale: False
    train_denominator: False
    self_connection_type: 'linear'
        
train:
    train_shuffle: True
    random_seed: 616
    is_train_stress : True
    epoch: 200

    loss: 'Huber'
    loss_param:
        delta: 0.01

    optimizer: 'adam'
    optim_param:
        lr: 0.01
    scheduler: 'linearlr'
    scheduler_param:
        start_factor: 1.0
        total_iters: 200
        end_factor: 0.0001

    force_loss_weight : 1.00
    stress_loss_weight: 0.01

    error_record:
        - ['Energy', 'MAE']
        - ['Force', 'MAE']
        - ['Stress', 'MAE']
        - ['Energy', 'Loss']
        - ['Force', 'Loss']
        - ['Stress', 'Loss']
        - ['TotalLoss', 'None']

    per_epoch: 10

    #continue:
    #   checkpoint: './checkpoint_10.pth'
    #   reset_optimizer: False
    #   reset_scheduler: False

data:
    batch_size: 64  # per GPU batch size, as the model trained with 32 GPUs, the effective batch size equals 4096.
    shift: 'elemwise_reference_energies'
    scale: 'per_atom_energy_std'
    
    save_by_train_valid: False
    load_trainset_path: '/user/hansw/Dataset/graphs/MPF/sevenn_data/MPF_train_6.pt'
    load_validset_path: '/user/hansw/Dataset/graphs/MPF/sevenn_data/MPF_valid_6.pt'
    load_testset_path: '/user/hansw/Dataset/graphs/MPF/sevenn_data/MPF_test_6.pt'


