model:
    chemical_species: 'auto'
    cutoff: 5.0
    channel: 128
    is_parity: False
    lmax: 3
    num_convolution_layer: 3
    irreps_manual:
        - "128x0e"
        - "128x0e+64x1e+32x2e+32x3e"
        - "128x0e+64x1e+32x2e+32x3e"
        - "128x0e"

    weight_nn_hidden_neurons: [64, 64]
    radial_basis:
        radial_basis_name: 'bessel'
        bessel_basis_num: 8
    cutoff_function:
        cutoff_function_name: 'XPLOR'
        cutoff_on: 4.5

    act_gate: {'e': 'silu', 'o': 'tanh'}
    act_scalar: {'e': 'silu', 'o': 'tanh'}

    train_shift_scale: False
    train_denominator: False
    self_connection_type: 'linear'
train:
    train_shuffle: True
    random_seed: 1
    is_train_stress : True
    epoch: 600

    loss_energy: 'Huber'
    loss_force: 'Huber'
    loss_stress: 'Huber'
    loss_energy_param:
        delta: 0.01
    loss_force_param:
        delta: 0.01
    loss_stress_param:
        delta: 0.01

    optimizer: 'adam'
    optim_param:
        lr: 0.01
    scheduler: 'linearlr'
    scheduler_param:
        start_factor: 1.0
        total_iters: 600
        end_factor: 0.0001

    force_loss_weight : 1.00
    stress_loss_weight: 0.01

    # Energy, Force, Stress, TotalLoss // supported as first arg
    # RMSE, ComponentRMSE, MAE, Loss // supported as second arg
    error_record:
        - ['Energy', 'axiswiseRMSE']
        - ['Energy', 'axiswiseMAE']
        - ['Force', 'axiswiseRMSE']
        - ['Force', 'L2RMSE']
        - ['Force', 'L2MAE']
        - ['Stress', 'axiswiseRMSE']
        - ['Stress', 'axiswiseMAE']
        - ['Energy', 'Loss']
        - ['Force', 'Loss']
        - ['Stress', 'Loss']
        - ['TotalLoss', 'None']

    per_epoch: 10
    # continue:
    #    checkpoint: './checkpoint_best.pth'
    #    reset_optimizer: False
    #    reset_scheduler: False
data:
    data_shuffle: False
    batch_size: 128
    shift: 'elemwise_reference_energies'

    data_format: 'ase'
    save_by_train_valid: False
    preprocess_num_cores: 96
    load_dataset_path: ["/home/sr5/zetta/DB/materials_projects/chgnet/chgnet_total_dataset_uncorrected.sevenn_data"]
    load_validset_path: ["/home/sr5/zetta/DB/materials_projects/chgnet/chgnet_val_dataset_uncorrected.sevenn_data"]


